### ISSUE TITLE
Site Footer

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#10]
- [x] Include Site Logo component
- [x] Description
- [x] Include project contact information (#12)
- [x] Include Copyright component (#13)
- [x] Navigation: use site navigation component (#11)
- [x] Learn More About (organization names & links)
  - [x] CSIS
  - [x] SWF
  - [x] UT
