### ISSUE TITLE
Create Post Collection

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#5]
Analysis posts will be stored as markdown files in the `/analysis` directory. Note that the tasks in "Set up in Nuxt" must be completed first.

## Set up in Nuxt
- [x] Create `analysis` directory
- [x] Set up dynamic routing
- [x] Process front matter

## Set up front matter templates in Forestry
- [x] Title
- [x] Date ("date" field)
- [x] Last Updated ("date" field)
- [x] Excerpt
- [x] Feature Image
  - [x] Image
  - [x] Caption
- [x] Authors ("sortable list", pull from `authors` data file (#6))
- [x] Event Types ("sortable list", pull from `event_types` data file (#7))
- [x] Tags ("sortable list", pull from `tags` data file(#7))
- [x] Related Satellites ("sortable list", pull from `satellites` data file (#8))
- [x] Related posts ("sortable list", pull from `analysis` data file: `/content/analysis.json`)
- [x] Further Reading ("repeatable field group")
  - [x] Name
  - [x] Author
  - [x] URL

**Comment by jnschrag** [comment]
@shortjared will be creating the CMS that includes these fields.
